# Generated by Django 2.2.16 on 2020-10-15 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_invent', models.CharField(max_length=5)),
                ('tipo', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Nobreak', 'Nobreak'), ('Roteador', 'Roteador'), ('Switch', 'Switch'), ('Smartphone', 'Smartphone'), ('Outros', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=700)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(max_length=20)),
                ('filial', models.CharField(choices=[('1', 'Matriz'), ('2', 'CD'), ('3', 'Zerão'), ('4', 'Congós'), ('5', 'Buritizal'), ('6', 'Sta Rita')], max_length=1)),
                ('local', models.CharField(max_length=20)),
                ('n_serie', models.CharField(blank=True, max_length=30, null=True)),
                ('end_ip', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('D', 'Desativo'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('ano_fab', models.DateField(blank=True, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado', models.DateTimeField(default=django.utils.timezone.now)),
                ('so_instalado', models.CharField(blank=True, choices=[('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Linux', 'Linux')], max_length=20, null=True)),
                ('tipo_memoria', models.CharField(blank=True, choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=20, null=True)),
                ('memoria_mb', models.CharField(blank=True, choices=[('2GBb', '2Gb'), ('4GBb', '4Gb'), ('6GBb', '6Gb'), ('8GBb', '8Gb'), ('10GBb', '10Gb'), ('12GBb', '12Gb'), ('16GBb', '16Gb')], max_length=20, null=True)),
                ('processador', models.CharField(blank=True, max_length=10, null=True)),
                ('processdor_ghz', models.CharField(blank=True, max_length=4, null=True)),
                ('nome_host', models.CharField(blank=True, max_length=40, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='equipamento_imagens/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=700)),
                ('inicio_garantia', models.DateField(blank=True, null=True)),
                ('fim_garantia', models.DateField(blank=True, null=True)),
                ('atendimento', models.CharField(max_length=700)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipamento')),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
            },
        ),
    ]
