# Generated by Django 2.2.16 on 2020-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201015_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='so_instalado',
            field=models.CharField(blank=True, choices=[('Windows XP', 'Windows XP'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Linux', 'Linux')], max_length=20, null=True, verbose_name='Sistema Operacional'),
        ),
    ]
